name: Python CI/CD

on:
  push:
    branches:
      - main  # Atur sesuai dengan nama cabang utama Anda
  pull_request:
    branches:
      - main  # Atur sesuai dengan nama cabang utama Anda

jobs:
  build:
    runs-on: ubuntu-latest  # Menggunakan sistem operasi Ubuntu terbaru

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # Atur sesuai versi Python yang Anda gunakan

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Tests
      run: |
        python -m unittestRizky